---
project:
  type: website

execute:
  cache: true

format:
  html:
    theme: darkly
  revealjs:
    auto-stretch: false
    callout-appearance: simple
    code-copy: true
    filters:
      - _filters/slugify.lua
    hash-type: number
    history: false
    incremental: false
    link-external-icon: true
    logo: favicon.ico
    mermaid:
      theme: dark
    menu:
      hideMissingTitles: true
      useTextContentForMissingTitles: false
    mobile-view-distance: 10
    preview-links: true
    slide-number: h/v
    theme: dark
    transition: fade
    view-distance: 10
  

website:
  favicon: favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://jamespjh.github.io
      - icon: github
        href: https://github.com/jamespjh/talks
  site-url: https://jamespjh.github.io/talks
  title: Talks by James Hetherington