Alias "/talks" "/var/www/html/talks"

<Directory "/var/www/html/talks">
    Require all granted
    Options -Indexes +FollowSymLinks
    AllowOverride None
</Directory>

# Ensure /docs/ canonical trailing slash
RedirectMatch 301 ^/talks$ /talks/